version = 0.1
[default.deploy.parameters]
stack_name = "cand11-image-generator"
s3_prefix = "cand11-image-generator"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
