name: Build and Deploy SAM Application

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./sam_lambda

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        
      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v1
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          
      - name: Build SAM Application
        run: sam build --use-container
        
      - name: Deploy SAM Application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name cand11-image-generator --s3-bucket pgr301-couch-explorers --capabilities CAPABILITY_IAM --region eu-west-1
