name: Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
defaults:
  run:
    working-directory: ./java_sqs_client
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Build and push to Docker Hub
        run: |
          rev=$(git rev-parse --short HEAD)
          docker build . -t image-generator
          docker tag image-generator lika027/image-generator:$rev
          docker tag image-generator lika027/image-generator:latest
          docker push lika027/image-generator:$rev
          docker push lika027/image-generator:latest
        
    